name: API Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  build-push-image-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::037045765538:role/GithubActionsRole
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Model download
      run: python -m model_downloader

    - name: Unit testing
      run: pytest

    - name: Linting
      run: pylint src

    - name: Build image
      run: docker build --platform linux/amd64 -t fiap-credit-score-classification-api .

    - name: Tag to ECR
      run: docker tag fiap-credit-score-classification-api:latest 037045765538.dkr.ecr.us-east-1.amazonaws.com/fiap-credit-score-classification-api:latest

    - name: Register in ECR
      run: docker push 037045765538.dkr.ecr.us-east-1.amazonaws.com/fiap-credit-score-classification-api:latest

    - name: Update Lambda
      run: aws lambda update-function-code --function-name fiap-credit-score-classification-api --image-uri 037045765538.dkr.ecr.us-east-1.amazonaws.com/fiap-credit-score-classification-api:latest